$path = Join-Path $PSScriptRoot '..\src\routeTree.gen.ts'
$content = @'
/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as RoleDashboardRouteImport } from './routes/role-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleDashboardRoute = RoleDashboardRouteImport.update({
  id: '/role-dashboard',
  path: '/role-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/join-us': typeof JoinUsRoute
  '/role-dashboard': typeof RoleDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/join-us': typeof JoinUsRoute
  '/role-dashboard': typeof RoleDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/join-us': typeof JoinUsRoute
  '/role-dashboard': typeof RoleDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin-login' | '/join-us' | '/role-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin-login' | '/join-us' | '/role-dashboard'
  id: '__root__' | '/' | '/admin' | '/admin-login' | '/join-us' | '/role-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  JoinUsRoute: typeof JoinUsRoute
  RoleDashboardRoute: typeof RoleDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-dashboard': {
      id: '/role-dashboard'
      path: '/role-dashboard'
      fullPath: '/role-dashboard'
      preLoaderRoute: typeof RoleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  JoinUsRoute: JoinUsRoute,
  RoleDashboardRoute: RoleDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
'@
[System.IO.File]::WriteAllText($path, $content, [System.Text.Encoding]::UTF8)
Write-Output "Wrote $path"
