/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewsDetailRouteImport } from './routes/news-detail'
import { Route as RoleDashboardRouteImport } from './routes/role-dashboard'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as ContactIndexRouteImport } from './routes/contact/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsDetailRoute = NewsDetailRouteImport.update({
  id: '/news-detail',
  path: '/news-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleDashboardRoute = RoleDashboardRouteImport.update({
  id: '/role-dashboard',
  path: '/role-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRouteWithChildren
  '/editorial': typeof EditorialRoute
  '/join-us': typeof JoinUsRoute
  '/news': typeof NewsRoute
  '/news-detail': typeof NewsDetailRoute
  '/role-dashboard': typeof RoleDashboardRoute
  '/startups': typeof StartupsRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/editorial': typeof EditorialRoute
  '/join-us': typeof JoinUsRoute
  '/news': typeof NewsRoute
  '/news-detail': typeof NewsDetailRoute
  '/role-dashboard': typeof RoleDashboardRoute
  '/startups': typeof StartupsRoute
  '/contact': typeof ContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRouteWithChildren
  '/editorial': typeof EditorialRoute
  '/join-us': typeof JoinUsRoute
  '/news': typeof NewsRoute
  '/news-detail': typeof NewsDetailRoute
  '/role-dashboard': typeof RoleDashboardRoute
  '/startups': typeof StartupsRoute
  '/contact/': typeof ContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/editorial'
    | '/join-us'
    | '/news'
    | '/news-detail'
    | '/role-dashboard'
    | '/startups'
    | '/contact/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/editorial'
    | '/join-us'
    | '/news'
    | '/news-detail'
    | '/role-dashboard'
    | '/startups'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/editorial'
    | '/join-us'
    | '/news'
    | '/news-detail'
    | '/role-dashboard'
    | '/startups'
    | '/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ContactRoute: typeof ContactRouteWithChildren
  EditorialRoute: typeof EditorialRoute
  JoinUsRoute: typeof JoinUsRoute
  NewsRoute: typeof NewsRoute
  NewsDetailRoute: typeof NewsDetailRoute
  RoleDashboardRoute: typeof RoleDashboardRoute
  StartupsRoute: typeof StartupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-detail': {
      id: '/news-detail'
      path: '/news-detail'
      fullPath: '/news-detail'
      preLoaderRoute: typeof NewsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-dashboard': {
      id: '/role-dashboard'
      path: '/role-dashboard'
      fullPath: '/role-dashboard'
      preLoaderRoute: typeof RoleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRoute
    }
  }
}

interface ContactRouteChildren {
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContactRoute: ContactRouteWithChildren,
  EditorialRoute: EditorialRoute,
  JoinUsRoute: JoinUsRoute,
  NewsRoute: NewsRoute,
  NewsDetailRoute: NewsDetailRoute,
  RoleDashboardRoute: RoleDashboardRoute,
  StartupsRoute: StartupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
